[build]
  command = "npm run generate && npm run functions"
  publish = "dist"
  functions = "functions"

[dev]
  publish = "public"
  functions = "functions"

[template.environment]
  STRIPE_PUBLISHABLE_KEY = "Add your Stripe publishable key here: pk_test_xxx"
  STRIPE_SECRET_KEY = "Add your Stripe secret key here: sk_test_xxx"
  STRIPE_WEBHOOK_SECRET = "[Optional] Add your webhook secret here: whsec_xxx"
