// Code generated by Slice Machine. DO NOT EDIT.

import AboutImage from './AboutImage';
import AboutText from './AboutText';
import BookInfo from './BookInfo';
import ContactInfo from './ContactInfo';
import Slider from './Slider';

export {
	AboutImage,
	AboutText,
	BookInfo,
	ContactInfo,
	Slider,
};

export const components = {
	about_image: AboutImage,
	about_text: AboutText,
	book_info: BookInfo,
	about_info: ContactInfo,
	slider: Slider,
};
